### ISSUE TITLE
Mobile footer design

### ISSUE THREAD

**Issue by Bsodoge** [manpreet2000/tabrizz#1]
Congrats on the product hunt launch! The name is perfect 😂 Just had a suggestion tho.

Currently on mobile the footer looks like this.

![image](https://github.com/manpreet2000/tabrizz/assets/79531561/4d04fd01-0f5f-4747-9af7-df70927639f3)

I feel like it would look better like this, what do you think?

![image](https://github.com/manpreet2000/tabrizz/assets/79531561/48aacf5c-d9e0-45f2-93e9-d9bc9606564e)

I'll happily open a pr and fix if needed.

**Comment by manpreet2000** [comment]
Definitely!  That's a good catch. Yeah sure please if you can fix that It would be great!
I'll be updating the readme with the setup. but for client, I think it's pretty forward reactjs `npm run start`. 
Let me know if you need anything else.

Thanks for contributing tho!!
